
namespace QuickCoding
{
    public enum StatusCode
    {
        //public
        NA = 0,
        Success,
        IndexOutOfRange,
        DataNotExist,
        DataAlreadyExist,
        NameStringError,
        NameAlreadyExist,
        CharSpacingError,
        CommandError,
        LookUpIndexError,
        ContentStringError,

        //template
        TypeError = 30,
        LaserPowerOutOfRange,
        MarkSpeedOutOfRange,
        JumpSpeedOutOfRange,
        JumpDelayOutOfRange,
        MarkDelayOutOfRange,
        PolyDelayOutOfRange,
        LaserOnDelayOutOfRange,
        LaserOffDelayOutOfRange,
        FrequencyOutOfRange,
        DelayRuleError,
        ActiveTemplateBad,
        DataMatrixUnitsIndexError,

        //date
        DateFormatError = 50,
        DateDelimiterError,

        //serial
        RepititionError = 60,
        PlacesError,

        //qr code
        SymbolSizeError = 70,
        EncodationError,
        WidthError,

        //mark
        JobOutOfRange = 80,
        ReadyToMarkIsOFF,
        MarkInProgress,
        MarkStopped,
        MarkStopIsON,
        MarkStartError,

        //system
        TimeFormatError = 90,
        CommandExecuting,
        MarkingDelayError,
        SaveDataError,
        GuideLaserError,
        PermissionDenied,

        //setrow
        ROW1_FONTSIZE_OUT_OF_RANGE = 100,
        ROW1_FONT_NOT_EXIST = 101,
        ROW1_FONT_NOT_CHINESE = 102,
        ROW1_V1_IndexError = 111,
        ROW1_V1_DataNotExist,
        ROW1_V1_TypeError,
        ROW1_V2_IndexError = 121,
        ROW1_V2_DataNotExist,
        ROW1_V2_TypeError,
        ROW1_V3_IndexError = 131,
        ROW1_V3_DataNotExist,
        ROW1_V3_TypeError,
        ROW1_V4_IndexError = 141,
        ROW1_V4_DataNotExist,
        ROW1_V4_TypeError,
        ROW1_V5_IndexError = 151,
        ROW1_V5_DataNotExist,
        ROW1_V5_TypeError,

        ROW2_FONTSIZE_OUT_OF_RANGE = 200,
        ROW2_FONT_NOT_EXIST = 201,
        ROW2_FONT_NOT_CHINESE = 202,
        ROW2_V1_IndexError = 211,
        ROW2_V1_DataNotExist,
        ROW2_V1_TypeError,
        ROW2_V2_IndexError = 221,
        ROW2_V2_DataNotExist,
        ROW2_V2_TypeError,
        ROW2_V3_IndexError = 231,
        ROW2_V3_DataNotExist,
        ROW2_V3_TypeError,
        ROW2_V4_IndexError = 241,
        ROW2_V4_DataNotExist,
        ROW2_V4_TypeError,
        ROW2_V5_IndexError = 251,
        ROW2_V5_DataNotExist,
        ROW2_V5_TypeError,

        ROW3_FONTSIZE_OUT_OF_RANGE = 300,
        ROW3_FONT_NOT_EXIST = 301,
        ROW3_FONT_NOT_CHINESE = 302,
        ROW3_V1_IndexError = 311,
        ROW3_V1_DataNotExist,
        ROW3_V1_TypeError,
        ROW3_V2_IndexError = 321,
        ROW3_V2_DataNotExist,
        ROW3_V2_TypeError,
        ROW3_V3_IndexError = 331,
        ROW3_V3_DataNotExist,
        ROW3_V3_TypeError,
        ROW3_V4_IndexError = 341,
        ROW3_V4_DataNotExist,
        ROW3_V4_TypeError,
        ROW3_V5_IndexError = 351,
        ROW3_V5_DataNotExist,
        ROW3_V5_TypeError,

        ROW4_FONTSIZE_OUT_OF_RANGE = 400,
        ROW4_FONT_NOT_EXIST = 401,
        ROW4_FONT_NOT_CHINESE = 402,
        ROW4_V1_IndexError = 411,
        ROW4_V1_DataNotExist,
        ROW4_V1_TypeError,
        ROW4_V2_IndexError = 421,
        ROW4_V2_DataNotExist,
        ROW4_V2_TypeError,
        ROW4_V3_IndexError = 431,
        ROW4_V3_DataNotExist,
        ROW4_V3_TypeError,
        ROW4_V4_IndexError = 441,
        ROW4_V4_DataNotExist,
        ROW4_V4_TypeError,
        ROW4_V5_IndexError = 451,
        ROW4_V5_DataNotExist,
        ROW4_V5_TypeError,

        ROW5_FONTSIZE_OUT_OF_RANGE = 500,
        ROW5_FONT_NOT_EXIST = 501,
        ROW5_FONT_NOT_CHINESE = 502,
        ROW5_V1_IndexError = 511,
        ROW5_V1_DataNotExist,
        ROW5_V1_TypeError,
        ROW5_V2_IndexError = 521,
        ROW5_V2_DataNotExist,
        ROW5_V2_TypeError,
        ROW5_V3_IndexError = 531,
        ROW5_V3_DataNotExist,
        ROW5_V3_TypeError,
        ROW5_V4_IndexError = 541,
        ROW5_V4_DataNotExist,
        ROW5_V4_TypeError,
        ROW5_V5_IndexError = 551,
        ROW5_V5_DataNotExist,
        ROW5_V5_TypeError,

        FontFamilyError = 1000,
        FontSizeError,
        Row1Error,
        Row2Error,
        Row3Error,
        Row4Error,
        Row5Error,
    }
}
